### ISSUE TITLE
Third party libraries

### ISSUE THREAD

**Issue by filmackay** [observablehq/stdlib#103]
A new user to ObservableHQ: there is a lot of amazing stuff in here.

Unfortunately, I came unstuck (and haven't been able to migrate away from Jupyter) due to lack of 3rd party library support. I simply couldn't find a way to get something simple like  `googleapis` from npm to work. It took a while to understand the peculiarities of importing a npm module; but there seem to be many (non-D3) packages that simply can't be used.

I noticed all the usage of Google API's used raw REST and bypassed the modules provided by Google. Is this a transient or permanent one for ObservableHQ?

**Comment by mbostock** [comment]
Hi @filmackay. Indeed, the state of JavaScript libraries on the web right now is quite confusing. There are a mix of standards (or… conventions) used by published libraries, including:

1. Global exports (`window.foo = …` as a side-effect of loading the script)
2. CommonJS (require as popularized by Node.js)
3. [AMD](https://en.wikipedia.org/wiki/Asynchronous_module_definition) (the asynchronous module definition, *a.k.a.* require for the web)
4. [ES modules and imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) (the standard for the future)

This chaos stems from JavaScript’s lack of a module system for decades. If you’re used to Node, then you’ve benefitted from the success of Node’s CommonJS module system, but this doesn’t work on the web where loading must be asynchronous. If you’re used to developing with a bundler such as Webpack, Babel or Rollup, this complexity is likewise hidden from you, but countless collective hours are lost when things don’t “just work” out of the box.

The future is the ES module standard, but until library authors publish their libraries using this standard, there will be some hoops required to get many published libraries working natively in the web. Fortunately, there are quite a few techniques available to get libraries working in the web. Start here:

https://observablehq.com/@observablehq/how-to-require-stubborn-modules

We also have a debugger which will try to guess the right strategy automatically:

https://observablehq.com/@tmcw/module-require-debugger

If you have more questions, please head over to our forums to ask for help (rather than using GitHub issues, which are for bugs and feature requests related to our open-source libraries):

https://talk.observablehq.com

If you share a notebook with us or tell us which libraries you’d like to use in the browser, we’d be happy to assist you in getting them working.
