### ISSUE TITLE
Generators.observe and Generator.queue throws a TypeError on the console (side effect)

### ISSUE THREAD

**Issue by asg017** [observablehq/stdlib#89]
(Note: might be a duplicate of #44, but that issue doesnt specifically mention the error)

If you create a Generator with `Generators.observe` or `Generator.queue`, and that generator updates in the observable runtime, it throws on error on the console. It doesn't effect the value of the cell, the cell still computes just fine, but it seems the Observable runtime is throwing an error for some reason.

The error I get on the console (in Chrome):

```
worker.327fbbc92318b…8621ada8bfc37b.js:2 Uncaught (in promise) TypeError: i is not a function
    at Object.return (worker.327fbbc92318b…8621ada8bfc37b.js:2)
    at worker.327fbbc92318b…8621ada8bfc37b.js:2

``` 

Notebook displaying the error: https://observablehq.com/d/a28ffdc308b73051

**Comment by tmcw** [comment]
🤔 Indeed, where this is failing is around the dispose method - this [return](https://github.com/observablehq/stdlib/blob/e5e8ad446ec8b8c8b238eefa2d7139776be4ff27/src/generators/queue.js#L23) is where it expects either `null` or a `dipose()` method, but instead it's getting a Promise. Potentially this is a breakage around async generators.

**Comment by mbostock** [comment]
Not a bug. But could be improved. Generators.observe doesn’t (currently) let you pass in an async *initialize* function. If you use an async function, your *dispose* callback will be a promise instead of a function, hence the type error.

Options:

1. Generators.observe could ignore the return value of *initialize* if it’s not a function. This seems like it would fail silently and be harder to debug. 

2. Generators.observe could await the promise to invoke the dispose function. This could mean dispose would never be called (as here because the promise is an infinite loop).

3. Generators.observe could throw an error immediately if *initialize* returns something that is not a function. This would make the error more obvious.

I vote for the third option. You’d want to rewrite the generator so that it terminated the infinite loop when the generator is disposed, anyway.
