### ISSUE TITLE
Adopt hyperscript for html literals?

### ISSUE THREAD

**Issue by mbostock** [observablehq/stdlib#94]
Our html tagged template literal could be better. For example, it could support event listeners, style objects, and automatic escaping of text. And maybe we might also want a mechanism to do efficient updates, too.

There’s a lot of related open-source work in this area, to boot, particularly around hyperscript. Here’s a proof of concept, but there are lots of other libraries to consider (see the awesome-hyperscript list):

https://observablehq.com/d/1c3d8d85581a6bc9

The hard part here is that we can’t do this in a backwards-compatible way. So either we’ll need to introduce standard library versioning (which fortunately is easy relative to runtime versioning), or we’ll need to choose a new name, *e.g.* `htm` (but that won’t work for `svg` obviously). Either way it’s a bit tricky to change the behavior of a core standard library component.

**Comment by mbostock** [comment]
https://github.com/hyperhype/awesome-hyperscript
https://github.com/hyperhype/hyperscript
https://github.com/substack/hyperx
https://github.com/developit/htm

**Comment by tmcw** [comment]
More powerful HTML would definitely be a huge perk - I've found that I often split up my html template literal calls just to bind events on specific parts.

Just for the sake of completeness – and because I have a hunch it is worthwhile to explore – is JSX. It'd have no namespace problem, would endear us to the React crowd, would give us good CodeMirror highlighting off the bat (and good Monaco highlighting, if we go there). I think we could do it _without_ making React a requirement for the runtime, and we could add good enough pragma support that it'd work for Preact and other implementations too.

**Comment by mbostock** [comment]
https://observablehq.com/@observablehq/htl

**Comment by mbostock** [comment]
Fixed in #207.
